//! Compile `docs/guides/keyflow/*.md` into the site.
//!
//! The guide is read-only, so there is no reason to ship a markdown parser
//! to the browser: the whole thing is rendered here and the wasm bundle
//! carries finished HTML.
//!
//! This reads *outside the crate*, which the repo otherwise forbids
//! (see CLAUDE.md). The rule exists because `include_str!` across a
//! boundary is invisible to cargo and fails at compile time rather than
//! resolution time. A build script is the sanctioned way to do it: the
//! dependency is explicit, and `cargo:rerun-if-changed` makes cargo aware
//! of it, so editing a guide rebuilds the site.
//!
//! # Fence convention
//!
//! The guides already distinguish two kinds of Keyflow block, and the site
//! honours the distinction rather than inventing its own:
//!
//! - ` ```kf- ` — **source only**. Illustrates syntax, and often is not
//!   valid Keyflow on its own (the guides annotate these with `→` to
//!   explain what a form means). Rendered as a highlighted code block.
//! - ` ```kf+ ` — **engrave this**. A real chart fragment. Rendered live by
//!   the chart renderer, with a link that opens it in the editor.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    let guides = guides_dir();
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", guides.display());

    let mut pages: BTreeMap<(u32, String), String> = BTreeMap::new();

    let entries = std::fs::read_dir(&guides)
        .unwrap_or_else(|e| panic!("cannot read the guide directory {}: {e}", guides.display()));

    for entry in entries.flatten() {
        let path = entry.path();
        if path.extension().is_none_or(|e| e != "md") {
            continue;
        }
        println!("cargo:rerun-if-changed={}", path.display());

        let slug = path
            .file_stem()
            .expect("a .md path has a stem")
            .to_string_lossy()
            .into_owned();
        let raw = std::fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));

        let (front, body) = split_frontmatter(&raw);
        let title = front
            .get("title")
            .cloned()
            .unwrap_or_else(|| slug.replace('-', " "));
        let order: u32 = front
            .get("order")
            .and_then(|o| o.parse().ok())
            .unwrap_or(u32::MAX);

        pages.insert(
            (order, slug.clone()),
            render_page(&slug, &title, order, body),
        );
    }

    assert!(
        !pages.is_empty(),
        "no guide pages found in {} — the site would ship an empty guide",
        guides.display()
    );

    let mut out = String::from(
        "// @generated by build.rs from docs/guides/keyflow/*.md — do not edit.\n\
         pub static GUIDE_PAGES: &[GuidePage] = &[\n",
    );
    for page in pages.values() {
        out.push_str(page);
    }
    out.push_str("];\n");

    let dest = PathBuf::from(std::env::var_os("OUT_DIR").expect("cargo sets OUT_DIR"))
        .join("guide_generated.rs");
    std::fs::write(&dest, out).unwrap_or_else(|e| panic!("cannot write {}: {e}", dest.display()));
}

/// `<repo>/docs/guides/keyflow`, resolved from this crate's manifest dir so
/// it does not depend on the working directory cargo was invoked from.
fn guides_dir() -> PathBuf {
    let manifest = PathBuf::from(std::env::var_os("CARGO_MANIFEST_DIR").expect("cargo sets this"));
    let repo = manifest
        .parent()
        .and_then(Path::parent)
        .expect("apps/web is two levels below the repo root");
    repo.join("docs").join("guides").join("keyflow")
}

/// Split leading `---`-delimited YAML frontmatter from the body.
///
/// Deliberately not a YAML parser: the guides use flat `key: value` pairs,
/// and a dependency to read four scalars would not earn its place.
fn split_frontmatter(raw: &str) -> (BTreeMap<String, String>, &str) {
    let mut map = BTreeMap::new();
    let Some(rest) = raw.strip_prefix("---\n") else {
        return (map, raw);
    };
    let Some(end) = rest.find("\n---\n") else {
        return (map, raw);
    };
    for line in rest[..end].lines() {
        if let Some((k, v)) = line.split_once(':') {
            map.insert(k.trim().to_owned(), v.trim().to_owned());
        }
    }
    (map, &rest[end + "\n---\n".len()..])
}

/// Emit one `GuidePage { .. }` literal.
fn render_page(slug: &str, title: &str, order: u32, body: &str) -> String {
    let mut blocks = String::new();
    for block in split_blocks(body) {
        match block {
            Block::Markdown(md) => {
                let _ = write!(blocks, "        Block::Html({:?}),\n", markdown_to_html(md));
            }
            Block::Keyflow { source, engrave } => {
                let _ = write!(
                    blocks,
                    "        Block::Keyflow {{ source: {source:?}, engrave: {engrave} }},\n"
                );
            }
        }
    }
    format!(
        "    GuidePage {{\n        \
         slug: {slug:?},\n        title: {title:?},\n        order: {order},\n        \
         blocks: &[\n{blocks}        ],\n    }},\n"
    )
}

enum Block<'a> {
    Markdown(&'a str),
    Keyflow { source: &'a str, engrave: bool },
}

/// Split a page into prose runs and Keyflow fences.
///
/// Only `kf-` / `kf+` fences are pulled out; every other fence (```text,
/// bare ```) stays inside the prose and is rendered as an ordinary code
/// block by the markdown pass.
fn split_blocks(body: &str) -> Vec<Block<'_>> {
    let mut blocks = Vec::new();
    let mut rest = body;

    while let Some(open) = find_kf_fence(rest) {
        if open.start > 0 {
            blocks.push(Block::Markdown(&rest[..open.start]));
        }
        let after_open = &rest[open.body_start..];
        match after_open.find("\n```") {
            Some(close) => {
                blocks.push(Block::Keyflow {
                    source: after_open[..close].trim_matches('\n'),
                    engrave: open.engrave,
                });
                rest = after_open[close..]
                    .strip_prefix("\n```")
                    .unwrap_or("")
                    .trim_start_matches(|c| c != '\n');
            }
            // Unterminated fence: treat the remainder as prose rather than
            // silently swallowing the rest of the page.
            None => {
                blocks.push(Block::Markdown(&rest[open.start..]));
                rest = "";
                break;
            }
        }
    }
    if !rest.is_empty() {
        blocks.push(Block::Markdown(rest));
    }
    blocks
}

struct Fence {
    start: usize,
    body_start: usize,
    engrave: bool,
}

fn find_kf_fence(hay: &str) -> Option<Fence> {
    for (marker, engrave) in [("```kf+\n", true), ("```kf-\n", false)] {
        if let Some(start) = find_at_line_start(hay, marker) {
            return Some(Fence {
                start,
                body_start: start + marker.len(),
                engrave,
            });
        }
    }
    None
}

/// Find `needle` only where it begins a line — a fence inside an indented
/// block or mid-sentence is not a fence.
fn find_at_line_start(hay: &str, needle: &str) -> Option<usize> {
    let mut from = 0;
    while let Some(hit) = hay[from..].find(needle) {
        let at = from + hit;
        if at == 0 || hay.as_bytes()[at - 1] == b'\n' {
            return Some(at);
        }
        from = at + 1;
    }
    None
}

/// Rewrite Obsidian-style wiki links into guide routes.
///
/// The guides are vault notes as well as site pages, and they cross-link
/// each other as `[[slug]]` or `[[slug|Label]]`. Left alone those render as
/// literal brackets, which is what the first build of the site shipped.
/// Rewritten *before* the markdown pass so the result is an ordinary link.
fn wiki_links_to_markdown(md: &str) -> String {
    let mut out = String::with_capacity(md.len());
    let mut rest = md;

    while let Some(open) = rest.find("[[") {
        out.push_str(&rest[..open]);
        let after = &rest[open + 2..];
        let Some(close) = after.find("]]") else {
            // Unclosed: leave the text exactly as written rather than
            // swallowing the remainder of the page.
            out.push_str(&rest[open..]);
            return out;
        };
        let (target, label) = match after[..close].split_once('|') {
            Some((t, l)) => (t.trim(), l.trim()),
            None => {
                let t = after[..close].trim();
                (t, t)
            }
        };
        out.push_str(&format!("[{label}](/guide/{target})"));
        rest = &after[close + 2..];
    }
    out.push_str(rest);
    out
}

fn markdown_to_html(md: &str) -> String {
    use pulldown_cmark::{Options, Parser, html};

    let md = wiki_links_to_markdown(md);

    let mut options = Options::empty();
    options.insert(Options::ENABLE_TABLES);
    options.insert(Options::ENABLE_STRIKETHROUGH);
    options.insert(Options::ENABLE_FOOTNOTES);

    let mut out = String::new();
    html::push_html(&mut out, Parser::new_ext(&md, options));
    out
}
