//! Compile `docs/guides/keyflow/*.md` into the site.
//!
//! The guide is a **vault**: the files under `docs/guides/keyflow/` are
//! wiki notes with frontmatter, `[[wikilink]]` cross-references, and
//! Keyflow fences. The site does not pre-render them — it ships the
//! markdown and renders it through the real editor in read-only mode, so
//! the guide gets wikilink navigation, folds and the ```kf fence family
//! for free rather than through a bespoke markdown pass that would drift
//! from the editor's.
//!
//! (It did have such a pass, briefly. Replacing it with the editor is why
//! this file lost its markdown renderer and its fence splitter — both
//! were reimplementing, less well, something the editor already does.)
//!
//! So this build script does very little: read the notes, pull `title`,
//! `order` and `stage` out of the frontmatter for the table of contents,
//! and emit the
//! bodies as `&'static str`. That same text feeds the knowledge graph,
//! which is built in the browser.
//!
//! It reads *outside the crate*, which the repo otherwise forbids (see
//! CLAUDE.md). The rule exists because `include_str!` across a boundary is
//! invisible to cargo and fails at compile time rather than resolution
//! time. A build script is the sanctioned way: the dependency is explicit,
//! and `cargo:rerun-if-changed` makes cargo aware of it, so editing a
//! guide page rebuilds the site.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    let guides = guides_dir();
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", guides.display());

    let mut pages: BTreeMap<(u32, String), String> = BTreeMap::new();

    let entries = std::fs::read_dir(&guides)
        .unwrap_or_else(|e| panic!("cannot read the guide directory {}: {e}", guides.display()));

    for entry in entries.flatten() {
        let path = entry.path();
        if path.extension().is_none_or(|e| e != "md") {
            continue;
        }
        println!("cargo:rerun-if-changed={}", path.display());

        let slug = path
            .file_stem()
            .expect("a .md path has a stem")
            .to_string_lossy()
            .into_owned();
        let raw = std::fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));

        let front = frontmatter(&raw);
        let title = fm_scalar(front, "title").unwrap_or_else(|| slug.replace('-', " "));
        let order: u32 = fm_scalar(front, "order")
            .and_then(|o| o.parse().ok())
            .unwrap_or(u32::MAX);
        // The stage this chapter belongs to, for the table of contents.
        // The index page has none — it is the front door, not a step.
        let stage = fm_scalar(front, "stage").unwrap_or_default();

        // Two forms of the same note, and they are not interchangeable:
        //
        // `source` keeps the frontmatter, because the graph builder reads
        // `type:` out of it to classify nodes.
        //
        // `body` drops it, because that is what the editor renders. The
        // editor treats frontmatter as an editable property table — right
        // for a vault app, wrong for a published guide, where it shows up
        // as a "+ Add property" button above the first heading.
        let body = strip_frontmatter(&raw);
        let mut lit = String::new();
        let _ = write!(
            lit,
            "    GuidePage {{\n        slug: {slug:?},\n        title: {title:?},\n        \
             order: {order},\n        stage: {stage:?},\n        source: {raw:?},\n        \
             body: {body:?},\n    }},\n"
        );
        pages.insert((order, slug), lit);
    }

    assert!(
        !pages.is_empty(),
        "no guide pages found in {} — the site would ship an empty guide",
        guides.display()
    );

    let mut out = String::from(
        "// @generated by build.rs from docs/guides/keyflow/*.md — do not edit.\n\
         pub static GUIDE_PAGES: &[GuidePage] = &[\n",
    );
    for page in pages.values() {
        out.push_str(page);
    }
    out.push_str("];\n");

    let dest = PathBuf::from(std::env::var_os("OUT_DIR").expect("cargo sets OUT_DIR"))
        .join("guide_generated.rs");
    std::fs::write(&dest, out).unwrap_or_else(|e| panic!("cannot write {}: {e}", dest.display()));
}

/// `<repo>/docs/guides/keyflow`, resolved from this crate's manifest dir so
/// it does not depend on the working directory cargo was invoked from.
fn guides_dir() -> PathBuf {
    let manifest = PathBuf::from(std::env::var_os("CARGO_MANIFEST_DIR").expect("cargo sets this"));
    let repo = manifest
        .parent()
        .and_then(Path::parent)
        .expect("apps/web is two levels below the repo root");
    repo.join("docs").join("guides").join("keyflow")
}

/// The note with its frontmatter block removed.
fn strip_frontmatter(raw: &str) -> &str {
    let Some(rest) = raw.strip_prefix("---\n") else {
        return raw;
    };
    match rest.find("\n---") {
        // +4 for the closing "\n---", then past its line ending.
        Some(end) => rest[end + 4..].trim_start_matches(['\r', '\n']),
        None => raw,
    }
}

/// The `---`-delimited frontmatter block, without its fences.
fn frontmatter(raw: &str) -> &str {
    let Some(rest) = raw.strip_prefix("---\n") else {
        return "";
    };
    rest.find("\n---").map_or("", |end| &rest[..end])
}

/// Read a flat `key: value` line out of a frontmatter block.
///
/// Deliberately not a YAML parser: the guides use flat scalars, and a
/// dependency to read two of them would not earn its place.
fn fm_scalar(front: &str, key: &str) -> Option<String> {
    front.lines().find_map(|line| {
        let (k, v) = line.split_once(':')?;
        (k.trim() == key).then(|| v.trim().trim_matches(['"', '\'']).to_owned())
    })
}
