//! The guide, as a vault.
//!
//! `docs/guides/keyflow/*.md` are wiki notes: frontmatter, `[[wikilink]]`
//! cross-references, and ```kf fences carrying real charts. `build.rs`
//! renders them — prose to HTML, charts to inline SVG through the host
//! engraver — and codegens the page table this module includes.
//!
//! Two consumers of the same text, as before:
//!
//! - the **page**, which renders finished HTML. It used to render
//!   through the editor in read-only mode; that bought wikilinks and
//!   engraved fences at the price of loading the editor to read a
//!   sentence. `ssg-build` does both at build time instead, and the
//!   editor now appears where it earns its keep: the workbench.
//! - the **graph**, which reads each note verbatim — `type:` classifies
//!   a node and the `[[wikilinks]]` are the edges — and draws how the
//!   concepts connect.

use dioxus::prelude::*;
use view_knowledge_graph::build::build_wiki_graph;
use view_knowledge_graph::model::WikiGraph;
use view_knowledge_graph::parse::WikiFile;

// `pub static VAULT: ssg::StaticVault`, from `build.rs`.
ssg::include_vault!();

/// The `@font-face` rules for the engraving typefaces.
///
/// A chart SVG names its typefaces rather than embedding them — sixty
/// charts each carrying their own copy would be a guide nobody could
/// load — so a page that shows charts links this once and every chart on
/// it resolves against the same download.
///
/// Linked rather than inlined, and for the same reason: it is megabytes
/// of embedded typeface, and inlining would send them again for every
/// chapter. Generated by `build.rs`, which emits only the families the
/// guide's charts actually name.
pub const CHART_FONTS: Asset = asset!("/assets/chart-fonts.css");

/// Where the guide is published, as a URL prefix.
///
/// Server-only because that is the only build that needs the path as a
/// *string*: `static_routes` enumerates the pages for the pre-render.
/// The browser navigates by `Route::GuidePage`, and `build.rs` resolves
/// `[[wikilinks]]` against its own copy — all three have to agree, and
/// they are checked by the pages resolving at all.
#[cfg(feature = "server")]
pub const BASE: &str = "/guide";

/// The whole guide as a link graph.
///
/// Built from each note's verbatim `source`, which is where the graph's
/// inputs are: `type:` in the frontmatter classifies a node, and the
/// `[[wikilinks]]` — including the ones in a nav footer that the
/// rendered prose drops — are the edges.
///
/// Uses this repo's `view-knowledge-graph` rather than the equivalent
/// helper in `ssg-ui`. They are the same crate; the difference is which
/// copy, and taking `ssg-ui`'s would pull task's architect pin
/// alongside this repo's. See `apps/web/Cargo.toml`.
#[must_use]
pub fn graph() -> WikiGraph {
    let files: Vec<WikiFile> = VAULT
        .pages
        .iter()
        .map(|page| WikiFile {
            name: format!("{}.md", page.slug),
            path: format!("{}.md", page.slug),
            content: page.source.to_owned(),
        })
        .collect();
    build_wiki_graph(&files)
}

/// The subgraph within one hop of `slug`.
///
/// This is the view that belongs beside a note: the concept you are
/// reading and everything it touches. The whole graph beside a single
/// page is a picture of the vault, not of the page.
#[must_use]
pub fn local_graph(graph: &WikiGraph, slug: &str) -> WikiGraph {
    let mut keep: Vec<String> = vec![slug.to_owned()];
    for edge in &graph.edges {
        if edge.source == slug && !keep.contains(&edge.target) {
            keep.push(edge.target.clone());
        }
        if edge.target == slug && !keep.contains(&edge.source) {
            keep.push(edge.source.clone());
        }
    }

    WikiGraph {
        nodes: graph
            .nodes
            .iter()
            .filter(|n| keep.contains(&n.id))
            .cloned()
            .collect(),
        // Every edge between kept nodes, not just those touching `slug`:
        // an edge between two neighbours is exactly the "these two are
        // also related" fact that makes a local graph worth drawing.
        edges: graph
            .edges
            .iter()
            .filter(|e| keep.contains(&e.source) && keep.contains(&e.target))
            .cloned()
            .collect(),
        communities: graph.communities.clone(),
    }
}
