//! The guide, as a vault.
//!
//! `docs/guides/*.md` are wiki notes: frontmatter, `[[wikilink]]`
//! cross-references, and ```kf fences carrying real charts. `build.rs`
//! renders them — prose to HTML, charts to inline SVG through the host
//! engraver — and codegens the page table this module includes.
//!
//! Two consumers of the same text, as before:
//!
//! - the **page**, which renders finished HTML. It used to render
//!   through the editor in read-only mode; that bought wikilinks and
//!   engraved fences at the price of loading the editor to read a
//!   sentence. `ssg-build` does both at build time instead, and the
//!   editor now appears where it earns its keep: the workbench.
//! - the **graph**, which reads each note verbatim — `type:` classifies
//!   a node and the `[[wikilinks]]` are the edges — and draws how the
//!   concepts connect.

use dioxus::prelude::*;
use view_knowledge_graph::model::WikiGraph;

// `pub static VAULT: ssg::StaticVault`, from `build.rs`.
ssg::include_vault!();
// `pub static APPENDIX: ssg::StaticVault`, from `build.rs`.
ssg::include_vault!("ssg_appendix.rs");

/// The guide, as the site should read it.
///
/// Ordinarily this is [`VAULT`] — the table `build.rs` baked in, which is
/// what makes a published chapter arrive as finished HTML.
///
/// Under `dev-guide` it is whatever the dev server last rendered from
/// `docs/guides`, so editing a chapter is a save rather than a
/// rebuild. See [`crate::guide_live`]. The baked table is still the
/// fallback, and still what the first paint uses.
///
/// Everything reads the guide through here rather than through the static
/// directly, so the two paths cannot drift.
#[must_use]
pub fn vault() -> &'static ssg::StaticVault {
    #[cfg(feature = "dev-guide")]
    if let Some(live) = *crate::guide_live::LIVE_VAULT.read() {
        return live;
    }
    &VAULT
}

/// The `@font-face` rules for the engraving typefaces.
///
/// A chart SVG names its typefaces rather than embedding them — sixty
/// charts each carrying their own copy would be a guide nobody could
/// load — so a page that shows charts links this once and every chart on
/// it resolves against the same download.
///
/// Linked rather than inlined, and for the same reason: it is megabytes
/// of embedded typeface, and inlining would send them again for every
/// chapter. Generated by `build.rs`, which emits only the families the
/// guide's charts actually name.
pub const CHART_FONTS: Asset = asset!("/assets/chart-fonts.css");

/// Where the guide is published, as a URL prefix.
///
/// Server-only because that is the only build that needs the path as a
/// *string*: `static_routes` enumerates the pages for the pre-render.
/// The browser navigates by `Route::GuidePage`, and `build.rs` resolves
/// `[[wikilinks]]` against its own copy — all three have to agree, and
/// they are checked by the pages resolving at all.
#[cfg(feature = "server")]
pub const BASE: &str = "/guide";

/// Where the appendix is published.
#[cfg(feature = "server")]
pub const APPENDIX_BASE: &str = "/appendix";

/// The appendix, as the site should read it.
///
/// A separate vault from [`vault`]: reference material rather than
/// reading order, at its own URL. Not live-reloaded — the dev server
/// watches the guide, and the appendix changes when the parser does.
#[must_use]
pub fn appendix() -> &'static ssg::StaticVault {
    &APPENDIX
}

/// The whole guide as a link graph.
///
/// Built from each note's verbatim `source`, which is where the graph's
/// inputs are: `type:` in the frontmatter classifies a node, and the
/// `[[wikilinks]]` — including the ones in a nav footer that the
/// rendered prose drops — are the edges.
///
/// `ssg-ui` builds it. This used to be a hand-copy of that function,
/// because `ssg-ui`'s `graph` feature reaches `view-knowledge-graph` and
/// — while this repo's architect tag differed from task's — taking it
/// pulled a second copy of the architect crates. One tag now, so there is
/// one implementation again.
#[must_use]
pub fn graph() -> WikiGraph {
    ssg_ui::vault_graph(*vault())
}

/// The subgraph within one hop of `slug`.
///
/// This is the view that belongs beside a note: the concept you are
/// reading and everything it touches. The whole graph beside a single
/// page is a picture of the vault, not of the page.
///
/// Also `ssg-ui`'s, and formerly copied here for the same reason as
/// [`graph`].
#[must_use]
pub fn local_graph(graph: &WikiGraph, slug: &str) -> WikiGraph {
    ssg_ui::local_graph(graph, slug)
}
