//! Source linking for bidirectional mapping
//!
//! Connects rendered chart elements back to their source text,
//! enabling click-to-highlight, in-place editing, and navigation.

use super::position::ChartPosition;
use super::semantic_role::SemanticRole;
use crate::parsing::TextSpan;
use facet::Facet;

/// Complete source linking information for a chart element.
///
/// Enables bidirectional mapping between rendered elements and source text:
/// - Click on rendered chord → highlight source text
/// - Edit source text → update rendered element
/// - Navigate by position → find source location
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, Facet)]
pub struct SourceLink {
    /// Text span in the original source.
    /// This is the byte range in the input text that generated this element.
    pub span: TextSpan,

    /// Position in the chart (musical coordinates).
    /// This is where the element appears in the rendered score.
    pub position: ChartPosition,

    /// Voice assignment (separate from position for multi-voice handling).
    /// Voice 0 is the default/main voice; higher numbers are additional voices.
    pub voice: u8,

    /// Semantic roles (an element can have multiple roles).
    /// e.g., a chord could be both `FirstInMeasure` and `SectionStart`.
    pub roles: Vec<SemanticRole>,

    /// Whether this element came from template expansion.
    /// True if the element was generated by section recall (e.g., just "vs" without content).
    pub from_template: bool,

    /// If from template, link to original template definition.
    /// This span points to where the template content was originally defined.
    pub template_span: Option<TextSpan>,
}

impl SourceLink {
    /// Create a new source link with basic information.
    #[must_use]
    pub fn new(span: TextSpan, position: ChartPosition) -> Self {
        Self {
            span,
            position,
            voice: 0,
            roles: Vec::new(),
            from_template: false,
            template_span: None,
        }
    }

    /// Create a source link for a template-expanded element.
    #[must_use]
    pub fn from_template(
        span: TextSpan,
        position: ChartPosition,
        template_span: TextSpan,
        template_section: String,
    ) -> Self {
        Self {
            span,
            position,
            voice: 0,
            roles: vec![SemanticRole::FromTemplate { template_section }],
            from_template: true,
            template_span: Some(template_span),
        }
    }

    /// Set the voice number.
    #[must_use]
    pub const fn with_voice(mut self, voice: u8) -> Self {
        self.voice = voice;
        self
    }

    /// Add a semantic role.
    #[must_use]
    pub fn with_role(mut self, role: SemanticRole) -> Self {
        self.roles.push(role);
        self
    }

    /// Add multiple semantic roles.
    #[must_use]
    pub fn with_roles(mut self, roles: impl IntoIterator<Item = SemanticRole>) -> Self {
        self.roles.extend(roles);
        self
    }

    /// Set the template span (marks element as from template).
    #[must_use]
    pub fn with_template_span(mut self, template_span: TextSpan) -> Self {
        self.from_template = true;
        self.template_span = Some(template_span);
        self
    }

    /// Check if element has a specific role.
    #[must_use]
    pub fn has_role(&self, role: &SemanticRole) -> bool {
        self.roles.contains(role)
    }

    /// Check if element has any of the given roles.
    #[must_use]
    pub fn has_any_role(&self, roles: &[SemanticRole]) -> bool {
        roles.iter().any(|r| self.roles.contains(r))
    }

    /// Check if element is first in its measure.
    #[must_use]
    pub fn is_first_in_measure(&self) -> bool {
        self.roles.contains(&SemanticRole::FirstInMeasure)
    }

    /// Check if element is first in its system.
    #[must_use]
    pub fn is_first_in_system(&self) -> bool {
        self.roles.contains(&SemanticRole::FirstInSystem)
    }

    /// Check if element marks a section start.
    #[must_use]
    pub fn is_section_start(&self) -> bool {
        self.roles
            .iter()
            .any(|r| matches!(r, SemanticRole::SectionStart { .. }))
    }

    /// Get the section type if this is a section start.
    #[must_use]
    pub fn section_type(&self) -> Option<&str> {
        self.roles.iter().find_map(|r| match r {
            SemanticRole::SectionStart { section_type } => Some(section_type.as_str()),
            _ => None,
        })
    }

    /// Get the effective source span (template span if from template, otherwise main span).
    /// Use this when you want to navigate to the "real" source definition.
    #[must_use]
    pub fn effective_span(&self) -> &TextSpan {
        self.template_span.as_ref().unwrap_or(&self.span)
    }

    /// Get the display span (main span, which shows where the element appears in current context).
    /// Use this when highlighting current usage, not original definition.
    #[must_use]
    pub const fn display_span(&self) -> &TextSpan {
        &self.span
    }
}

impl Default for SourceLink {
    fn default() -> Self {
        Self::new(TextSpan::default(), ChartPosition::default())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_new_source_link() {
        let span = TextSpan::with_location(10, 5, 3, 1);
        let position = ChartPosition::at_beat(4, 2);

        let link = SourceLink::new(span, position);

        assert_eq!(link.span.start, 10);
        assert_eq!(link.position.measure, 4);
        assert_eq!(link.voice, 0);
        assert!(link.roles.is_empty());
        assert!(!link.from_template);
    }

    #[test]
    fn test_with_role() {
        let link = SourceLink::new(TextSpan::new(0, 5), ChartPosition::default())
            .with_role(SemanticRole::FirstInMeasure)
            .with_role(SemanticRole::SectionStart {
                section_type: "Verse".to_string(),
            });

        assert!(link.is_first_in_measure());
        assert!(link.is_section_start());
        assert_eq!(link.section_type(), Some("Verse"));
    }

    #[test]
    fn test_from_template() {
        let span = TextSpan::with_location(100, 2, 10, 1); // "vs" recall
        let template_span = TextSpan::with_location(20, 30, 3, 1); // Original definition
        let position = ChartPosition::at_measure(8);

        let link = SourceLink::from_template(span, position, template_span, "Verse".to_string());

        assert!(link.from_template);
        assert!(link.template_span.is_some());
        assert_eq!(link.effective_span().start, 20); // Points to original
        assert_eq!(link.display_span().start, 100); // Points to recall site
    }

    #[test]
    fn test_has_any_role() {
        let link = SourceLink::new(TextSpan::new(0, 5), ChartPosition::default())
            .with_role(SemanticRole::FirstInMeasure);

        assert!(link.has_any_role(&[SemanticRole::FirstInMeasure, SemanticRole::FirstInSystem]));
        assert!(!link.has_any_role(&[SemanticRole::LastInMeasure, SemanticRole::Pickup]));
    }

    #[test]
    fn test_with_voice() {
        let link = SourceLink::new(TextSpan::new(0, 5), ChartPosition::default()).with_voice(2);

        assert_eq!(link.voice, 2);
    }
}
